from django.shortcuts import render, redirect
from django.http import HttpResponse
from .forms import ContactForm, UploadFileForm
from .models import UploadedFile
import pefile
import os
import hashlib
from django.conf import settings

# New Home Page View (for '/')
def home(request):
    """
    Renders the main site homepage.
    """
    # This view uses a template from the root 'templates' folder
    return render(request, "home.html")

def security_logs(request):
    """
    Reads the text reports generated by Bandit and the Fuzzer
    and displays them on the web page.
    """
    # Define paths to the reports (assumes they are in the project root)
    base_dir = settings.BASE_DIR
    bandit_path = os.path.join(base_dir, 'bandit_report.txt')
    fuzzer_path = os.path.join(base_dir, 'fuzzer_report.txt')
    
    reports = {}
    
    # Read Bandit Report
    if os.path.exists(bandit_path):
        with open(bandit_path, 'r') as f:
            reports['bandit'] = f.read()
    else:
        reports['bandit'] = "Report not found. Run: bandit -r . -f txt -o bandit_report.txt"

    # Read Fuzzer Report
    if os.path.exists(fuzzer_path):
        with open(fuzzer_path, 'r') as f:
            reports['fuzzer'] = f.read()
    else:
        reports['fuzzer'] = "Report not found. Run: python3 fuzzer.py > fuzzer_report.txt"

    return render(request, 'polls/security_logs.html', {'reports': reports})

def upload_file(request):
    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.file_name = request.FILES['file'].name
            
            # --- CAPSTONE COMPONENT 4: ANALYSIS LOGIC HERE ---
            # run_security_scan(instance.file) 
            # instance.has_aslr = check_aslr(instance.file)
            
            instance.save()
            return redirect('index')
    else:
        form = UploadFileForm()
    return render(request, 'polls/upload.html', {'form': form})

def index(request):
    """
    Renders the polls app index page.
    """
    # This view uses a template from the 'templates/polls' folder
    # We are changing this from HttpResponse to render()
    return render(request, "polls/index.html")

def upload_analysis(request):
    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)
            uploaded_file = request.FILES['file']
            instance.file_name = uploaded_file.name
            
            # 1. SHA-256 Hash
            sha256_hash = hashlib.sha256()
            for chunk in uploaded_file.chunks():
                sha256_hash.update(chunk)
            instance.sha256_hash = sha256_hash.hexdigest()
            
            # Save initially to get file path
            instance.save()
            
            # 2. Analysis Logic
            try:
                file_path = instance.file.path
                pe = pefile.PE(file_path)
                
                # Reset flags first (assume False)
                instance.has_aslr = False
                instance.has_dep = False

                if pe.OPTIONAL_HEADER.DllCharacteristics & 0x0040:
                    instance.has_aslr = True
                
                if pe.OPTIONAL_HEADER.DllCharacteristics & 0x0100:
                    instance.has_dep = True
                
                pe.close()

                # --- CRITICAL: Mark UNSAFE if missing protections ---
                if not instance.has_aslr or not instance.has_dep:
                    instance.is_safe = False
                else:
                    instance.is_safe = True
                # ----------------------------------------------------

            except Exception as e:
                print(f"Analysis Error: {e}")
                # Optional: If it's not a PE file, is it safe? 
                # Let's say False to be cautious, or True if you only care about PE files.
                instance.is_safe = False 
            
            instance.save()
            return redirect('dashboard')
    else:
        form = UploadFileForm()
    
    return render(request, 'polls/upload_page.html', {'form': form})
    
def dashboard(request):
    files = UploadedFile.objects.all().order_by('-uploaded_at')
    return render(request, 'polls/dashboard.html', {'files': files})

# New Form Page View (for '/polls/form/')
def form_page(request):
    """
    Renders a page with a form.
    - Handles GET requests by showing a blank form.
    - Handles POST requests by validating the form and showing
      the sanitized submitted data.
    """
    submitted_name = None
    
    if request.method == "POST":
        # Create a form instance and populate it with data from the request:
        form = ContactForm(request.POST)
        
        # form.is_valid() runs all validation and sanitization
        if form.is_valid():
            # Process the data in form.cleaned_data
            # This data is sanitized and safe to use.
            submitted_name = form.cleaned_data['name']
            
            # For this example, we'll just re-render the page
            # with a success message. We pass in a new, blank form.
            return render(request, "polls/form_page.html", {
                "form": ContactForm(),
                "submitted_name": submitted_name
            })
    
    # if a GET (or any other method) we'll create a blank form
    else:
        form = ContactForm()

    return render(request, "polls/form_page.html", {
        "form": form
    })


# New Vulnerable Page View (for '/polls/vulnerable/')
def vulnerable_page(request):
    """
    Renders a page with an intentional security vulnerability.
    """
    # Get a 'name' parameter from the URL (e.g., ?name=User)
    # This input is NOT sanitized by the view.
    raw_name = request.GET.get('name', 'Guest')
    
    # We pass this raw, un-sanitized data directly to the template.
    # The vulnerability will be in the template itself.
    return render(request, "polls/vulnerable_page.html", {
        "name": raw_name
    })
