# Generated by Django 4.2.25 on 2025-12-10 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_name', models.CharField(max_length=255)),
                ('has_dep', models.BooleanField(default=False)),
                ('has_aslr', models.BooleanField(default=False)),
                ('is_safe', models.BooleanField(default=True)),
            ],
        ),
    ]
