# Generated by Django 4.2.25 on 2025-12-11 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='sha256_hash',
            field=models.CharField(blank=True, help_text='SHA-256 Hash of the file', max_length=64),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='has_aslr',
            field=models.BooleanField(default=False, help_text='Address Space Layout Randomization'),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='has_dep',
            field=models.BooleanField(default=False, help_text='Data Execution Prevention'),
        ),
    ]
